# FROM ruby:2.3.4
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build


WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./*.sln ./
COPY ./API/API.csproj  ./API/API.csproj
COPY ./Infrastructure/Infrastructure.csproj  ./Infrastructure/Infrastructure.csproj
COPY ./Core/Core.csproj  ./Core/Core.csproj
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out 

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "API.dll"]