version: '3'
services:
  web:
    container_name: 'web-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:80'
    depends_on:
      - 'postgres' 

  postgres:
    image: postgres
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=appuser
      - POSTGRES_DB=ReturnOrderManagementDb

    expose: 
      - "5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  accman-postgresql-volume:
