apiVersion: apps/v1
kind: Deployment
metadata:
  name: returnorderserviceimage-deployment
  labels:
    app: returnorderserviceimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: returnorderserviceimage
  template:
    metadata:
      labels:
        app: returnorderserviceimage
    spec:
      containers:
      - name: returnorderserviceimage
        image: returnorderprojectcr.azurecr.io/returnorderserviceimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: returnordersvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: returnordermanagementservicesvc2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: returnorderserviceimage