apiVersion: apps/v1
kind: Deployment
metadata:
  name: returnordermanagement-deployment
  labels:
    app: ReturnOrderManagementService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ReturnOrderManagementService
  template:
    metadata:
      labels:
        app: ReturnOrderManagementService
    spec:
      containers:
      - name: returnordermanagementservice
        image: returnorderprojectcr.azurecr.io/returnorderserviceimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: returnordersvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: returnordermanagementservicesvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ReturnOrderManagementService